config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get '/auth/github', as: :github_login

  get '/auth/github/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :repos, only: [:index]
  resources :events, only: [:index]
end

app/models/event.rb
class Event
  attr_reader :user, :id, :type, :payload

  def initialize(user,event_hash)
    @user = user
    @id = event_hash[:id]
    @type = event_hash[:type]
    @payload = event_hash[:payload]
  end

  def self.all(user)
    service = UsersService.new
    raw_events = service.get_events(user)
    raw_events.map do |event|
      Event.new(user, event)
    end
  end

  def self.push_events(user)
    all_events = all(user)
    all_events.find_all do |event|
      event.type == "PushEvent"
    end
  end

  def self.payload_commit_data(user)
    push_events(user).map do |event|
      event.payload[:commits]
    end
  end

  def self.commits(user)
    payload_commit_data(user).map do |data|
      data.map do |commit|
        OpenStruct.new(commit)
      end
    end.flatten
  end

end

app/models/repo.rb
class Repo
  attr_reader :user, :name

  def initialize(user, new_repos_hash)
    @user      = user
    @id        = new_repos_hash["id"]
    @name      = new_repos_hash["name"]
    @full_name = new_repos_hash["full_name"]
    @owner     = new_repos_hash["owner"]["login"]
  end

  def self.all(user)
    r = ReposService.new
    raw_repos = r.get_repos(user)
    raw_repos.map do |repo|
      Repo.new(user,repo)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    user = User.find_or_create_by(uid: auth_info[:uid])
    user.update_attributes(
      uid:         auth_info.uid,
      nickname:    auth_info.info.nickname,
      profile_pic: auth_info.info.image,
      oauth_token: auth_info.credentials.token,
      followers:   auth_info.extra.raw_info.followers,
      following:   auth_info.extra.raw_info.following
    )
    user
  end

  def starred_count(user)
    UsersService.new.get_starred_repos(user).count
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @user = current_user
    @commits = Event.commits(@user)
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @user  = current_user
    @repos = Repo.all(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<%= render partial: 'shared/navbar' %>
<h1>Recent Commits </h1>
<ul>
  <% @commits.each do |commit| %>
      <li><%= commit.sha %><br><%= commit.message %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LitHub</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<div class="container">
  <body>
  <%= yield %>

  </body>
  <div class="bottom_padding"></div>
</div>
</html>

app/views/repos/index.html.erb
<%= render partial: "shared/navbar" %>

<h1>My Repos</h1>
<div class="container">
  <ul>
    <% @repos.each do |repo| %>
      <li> <%= repo.name %></li>
    <% end  %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      </button>
      <a class="navbar-brand" href="/">LitHub</a>
    </div>

  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><a>Welcome, <%= current_user.nickname %></a></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In with Github", github_login_path %></li>
      <% end  %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<%= render partial: 'shared/navbar' %>
<% if current_user %>
<div class="row">
  <div class="container basic-info col-md-6">
    <div class="profile-pic">
      <img id="profile_pic" src="<%= @user.profile_pic %>" alt="profile-pic" />
    </div>
    <div class="username">
      <h1><%= @user.nickname %></h1>
    </div>
    <div class="row stats">
      <div class="col-md-2 text-center" id="followers">
        <%= @user.followers %><br>
        <p>followers</p>
      </div>
      <div class="col-md-2 text-center" id="starred">
        <%= @user.starred_count(current_user) %><br>
        <p>starred</p>
      </div>
      <div  class="col-md-2 text-center" id="following">
        <%= @user.following %><br>
        <p>following</p>
      </div>
    </div>
  </div>

  <div class='col-md-6'>
    <div class='btn btn-large btn-info column-md-6'><%= link_to "My Repos", repos_path, class: "info_link" %></div>
    <div class='btn btn-large btn-info column-md-6'><%= link_to "Recent Commits", events_path, class: "info_link" %></div>
  </div>
</div>
<% end %>